import os

pipeline_yaml_content = """
name: CI/CD Pipeline for Streamlit Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Deploy to Streamlit Sharing
      run: |
        streamlit run your_app.py
      env:
        STREAMLIT_API_TOKEN: ${{ secrets.STREAMLIT_API_TOKEN }}
"""

with open('ci_cd_pipeline.yml', 'w') as file:
    file.write(pipeline_yaml_content)